export const CREATE_PRODUCT_TYPE_REQUEST = "CREATE_PRODUCT_TYPE_REQUEST";
export const CREATE_PRODUCT_TYPE_SUCCESS = "CREATE_PRODUCT_TYPE_SUCCESS";
export const CREATE_PRODUCT_TYPE_FAILURE = "CREATE_PRODUCT_TYPE_FAILURE";
