export const GET_LEVEL_ONE_CATEGORIES_REQUEST =
  "GET_LEVEL_ONE_CATEGORIES_REQUEST";
export const GET_LEVEL_ONE_CATEGORIES_SUCCESS =
  "GET_LEVEL_ONE_CATEGORIES_SUCCESS";
export const GET_LEVEL_ONE_CATEGORIES_FAILLURE =
  "GET_LEVEL_ONE_CATEGORIES_FAILLURE";

export const GET_SUBCATEGORIES_REQUEST = "GET_SUBCATEGORIES_REQUEST";
export const GET_SUBCATEGORIES_SUCCESS = "GET_SUBCATEGORIES_SUCCESS";
export const GET_SUBCATEGORIES_FAILURE = "GET_SUBCATEGORIES_FAILURE";
