export const CREATE_PRODUCT_METADATA_REQUEST = "CREATE_PRODUCT_METADATA_REQUEST";
export const CREATE_PRODUCT_METADATA_SUCCESS = "CREATE_PRODUCT_METADATA_SUCCESS";
export const CREATE_PRODUCT_METADATA_FAILURE = "CREATE_PRODUCT_METADATA_FAILURE";

export const GET_PRODUCT_METADATA_REQUEST = "GET_PRODUCT_METADATA_REQUEST";
export const GET_PRODUCT_METADATA_SUCCESS = "GET_PRODUCT_METADATA_SUCCESS";
export const GET_PRODUCT_METADATA_FAILURE = "GET_PRODUCT_METADATA_FAILURE";

export const UPDATE_PRODUCT_METADATA_REQUEST = "UPDATE_PRODUCT_METADATA_REQUEST";
export const UPDATE_PRODUCT_METADATA_SUCCESS = "UPDATE_PRODUCT_METADATA_SUCCESS";
export const UPDATE_PRODUCT_METADATA_FAILURE = "UPDATE_PRODUCT_METADATA_FAILURE";

export const DELETE_PRODUCT_METADATA_REQUEST = "DELETE_PRODUCT_METADATA_REQUEST";
export const DELETE_PRODUCT_METADATA_SUCCESS = "DELETE_PRODUCT_METADATA_SUCCESS";
export const DELETE_PRODUCT_METADATA_FAILURE = "DELETE_PRODUCT_METADATA_FAILURE";