export const GET_CATEGORY_HIERARCHY_REQUEST = "GET_CATEGORY_HIERARCHY_REQUEST";
export const GET_CATEGORY_HIERARCHY_SUCCESS = "GET_CATEGORY_HIERARCHY_SUCCESS";
export const GET_CATEGORY_HIERARCHY_FAILURE = "GET_CATEGORY_HIERARCHY_FAILURE";

export const GET_CATEGORY_ID_BY_PRODUCT_ID_REQUEST = "GET_CATEGORY_ID_BY_PRODUCT_ID_REQUEST";
export const GET_CATEGORY_ID_BY_PRODUCT_ID_SUCCESS = "GET_CATEGORY_ID_BY_PRODUCT_ID_SUCCESS";
export const GET_CATEGORY_ID_BY_PRODUCT_ID_FAILURE = "GET_CATEGORY_ID_BY_PRODUCT_ID_FAILURE";